version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: imdb-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: imdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: imdb
      POSTGRES_HOST: postgres
    depends_on:
      - postgres

volumes:
  postgres_data:
