# Generated by Django 5.0.6 on 2024-05-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nconst', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('year_of_birth', models.PositiveIntegerField()),
                ('year_of_death', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
