# Generated by Django 5.0.6 on 2024-05-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.AlterField(
            model_name='person',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='year_of_death',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
