# Generated by Django 5.0.6 on 2024-05-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_person_options_alter_person_year_of_birth_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='movies_pers_name_64a075_idx'),
        ),
    ]
