# Generated by Django 5.0.6 on 2024-05-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_person_movies_pers_name_64a075_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.CharField(max_length=16, unique=True)),
                ('primary_title', models.CharField(max_length=256)),
                ('original_title', models.CharField(max_length=256)),
                ('year', models.PositiveIntegerField()),
                ('runtime', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'indexes': [models.Index(fields=['primary_title'], name='movies_movi_primary_29eb16_idx'), models.Index(fields=['original_title'], name='movies_movi_origina_287505_idx')],
            },
        ),
    ]
