# Generated by Django 5.0.6 on 2024-05-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('short', 'Short Film'), ('movie', 'Feature Film')], default='movie', max_length=16),
        ),
    ]
