# Generated by Django 5.0.6 on 2024-05-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
