# Generated by Django 5.0.6 on 2024-05-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
