# Generated by Django 5.0.6 on 2024-05-12 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=256)),
                ('job', models.CharField(max_length=256)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies_as_crew', to='movies.person')),
            ],
            options={
                'verbose_name': 'crew member',
                'verbose_name_plural': 'crew members',
                'indexes': [models.Index(fields=['job_category'], name='movies_crew_job_cat_9153e7_idx'), models.Index(fields=['job'], name='movies_crew_job_e3a5c9_idx')],
            },
        ),
    ]
