# Generated by Django 5.0.6 on 2024-05-12 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_crewmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies_as_actor', to='movies.person')),
            ],
            options={
                'verbose_name': 'character',
                'verbose_name_plural': 'characters',
                'indexes': [models.Index(fields=['name'], name='movies_char_name_bb60a3_idx')],
            },
        ),
    ]
