# Generated by Django 5.0.6 on 2024-05-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_character_ordering_crewmember_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
