# Generated by Django 5.0.6 on 2024-05-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='job',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
