# Generated by Django 5.0.6 on 2024-05-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_crewmember_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
