# Generated by Django 5.0.6 on 2024-05-13 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_rating_movie_rating_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='movies.person'),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_works', to='movies.person'),
        ),
    ]
