# Generated by Django 5.0.6 on 2024-05-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_movie_tconst_alter_person_nconst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='movie',
            name='primary_title',
            field=models.CharField(max_length=512),
        ),
    ]
