# Generated by Django 5.0.6 on 2024-06-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_alter_movie_original_title_alter_movie_primary_title'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['year'], name='movies_movi_year_82d175_idx'),
        ),
    ]
